"""Build the Azqato Invests pages from the source snapshots in _sources/.

Run from anywhere: python scripts/site.py
Needs Python 3 and BeautifulSoup 4 (bs4). Reads _sources/ only; writes the
site's pages, the scoped source stylesheets, the copied source scripts,
assets/js/search-index.js, inventory/map.json and inventory/em-dashes.md.

Until the author's review after the MVP (Development plan P7), every page is
generated by this script: change the script, not the pages, and run it
again. Each page's content is its source page's content, moved whole (core
rule); only the site navigation around it is replaced by the shell built here.
"""
import html, json, pathlib, posixpath, re, shutil
from bs4 import BeautifulSoup, Comment, NavigableString

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "_sources"
TPL = SRC / "templateinterface"
TPL_COMMIT = "ed840da"
BRAND = "Azqato Invests"
CHARTJS = "https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"
CHARTJS_SRI = "sha384-e6nUZLBkQ86NJ6TVVKAeSaK8jWa3NhkYWZFomE39AvDbQWeie9PlQqM3pmYW5d1g"
VIX_FEED = "https://azqato.github.io/vix/data/vix.js"
STOCKS_DATA = "https://azqato.github.io/stocks/data/"
# The published address (D4, D21; changed 2026-10-02, Question 18): the invests/
# folder of the azqato.github.io repo, served at azqato.com by Cloudflare Pages.
SITE_URL = "https://azqato.com/invests/"

# path, source page, sidebar label, group, kind, parent path (for breadcrumbs)
PAGES = [
    ("index.html", "azqato.github.io/invests.html", "Home", None, "home", None),
    ("stocks/index.html", "stocks/index.html", "Individual Stocks", "Individual Stocks", "doc", None),
    ("stocks/philosophy.html", "stocks/philosophy.html", "Philosophy", "Individual Stocks", "doc", "stocks/index.html"),
    ("stocks/metrics.html", "stocks/metrics.html", "Stock metrics", "Individual Stocks", "doc", "stocks/index.html"),
    ("stocks/screener.html", "stocks/screener.html", "Screener", "Individual Stocks", "tool", "stocks/index.html"),
    ("indices/index.html", "stocks/indices.html", "Indices & ETFs", "Indices & ETFs", "doc", None),
    ("indices/market.html", "stocks/market.html", "Market Overview", "Indices & ETFs", "tool", "indices/index.html"),
    ("vix/index.html", "vix/index.html", "VIX Strategy", "VIX Strategy", "doc", None),
    ("vix/dashboard.html", "vix/strategy.html", "VIX Dashboard", "VIX Strategy", "tool", "vix/index.html"),
    ("vix/custom.html", "vix/custom.html", "VIX Custom builder", "VIX Strategy", "tool", "vix/index.html"),
    ("leveraged/index.html", "leverage/index.html", "Leveraged Strategies", "Leveraged Strategies", "doc", None),
    ("leveraged/3sig.html", "leverage/3sig.html", "3 Sig", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("leveraged/6sig.html", "leverage/6sig.html", "6 Sig", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("leveraged/9sig.html", "leverage/9sig.html", "9 Sig", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("leveraged/tqqq-ftlt.html", "leverage/tqqq-ftlt.html", "TQQQ FTLT", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("leveraged/holy-grail.html", "leverage/holy-grail.html", "Holy Grail", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("leveraged/hfea.html", "leverage/hfea.html", "HFEA", "Leveraged Strategies", "doc", "leveraged/index.html"),
    ("resources/index.html", "azqato.github.io/invests.html", "Curated resources", "Resources", "doc", None),
    ("resources/finviz.html", "stocks/finviz.html", "Finviz setup guide", "Resources", "doc", "resources/index.html"),
    ("resources/seekingalpha.html", "stocks/seekingalpha.html", "Seeking Alpha setup guide", "Resources", "doc", "resources/index.html"),
    ("resources/faq.html", "stocks/faq.html", "FAQ", "Resources", "doc", "resources/index.html"),
]
# Grouped by what the visitor invests in (restructure, 2026-10-02): each group's
# first page is its landing page; the sidebar lists it as "Overview" in the
# topic groups.
GROUPS = ["Individual Stocks", "Indices & ETFs", "VIX Strategy", "Leveraged Strategies", "Resources"]
TITLES = {"index.html": f"{BRAND} - Investing Tools and Resources"}

# azqato.com's top nav (D9), copied from azqato.github.io/invests.html at the
# snapshot commit; Invests points to this site.
AZQATO_NAV = [("Home", "https://azqato.com/"), ("About", "https://azqato.com/about"), ("Discord", "https://azqato.com/discord"),
              ("Invests", None), ("Codes", "https://azqato.com/codes"), ("Music", "https://azqato.com/music"),
              ("Links", "https://azqato.com/links"), ("Projects", "https://azqato.com/projects"),
              ("YouTube", "https://azqato.com/youtube"), ("Support", "https://azqato.com/support")]

# Old addresses (relative to each source, or absolute) to new pages.
LINKS = {}
for path, src, *_ in PAGES:
    repo, name = src.split("/")
    if repo == "azqato.github.io":
        continue
    LINKS[(repo, name)] = path
    LINKS[("abs", f"https://azqato.github.io/{repo}/{name}")] = path
    if name == "index.html":
        LINKS[("abs", f"https://azqato.github.io/{repo}/")] = path
        LINKS[("abs", f"https://azqato.github.io/{repo}")] = path
for u in ("https://azqato.com/invests", "https://azqato.github.io/invests.html"):
    LINKS[("abs", u)] = "index.html"
COMPOSER_OLD = re.compile(r"^https://azqato\.github\.io/composer/?(.*)$")

# Source site navigation and layout wrappers: replaced by the shell. Text in
# KEEP is moved into the page's source footer block instead of being dropped.
CHROME = {
    "stocks": {"remove": ["aside.sidebar"], "keep": [".sidebar-footer"], "unwrap": [".site-wrapper", ".site-layout"],
               "css_drop": ["sidebar", "sidebar-brand", "sidebar-brand-sub", "sidebar-nav", "nav-toggle", "nav-burger",
                            "nav-section-label", "metric-links", "site-wrapper", "site-layout", "main-content"]},
    "vix": {"remove": ["header.site-header"], "keep": [], "unwrap": [],
            "css_drop": ["site-header", "nav-container", "nav-brand", "nav-logo", "nav-title", "nav-links", "nav-link", "nav-active"]},
    "leverage": {"remove": ["a.skip-link", "nav.top-bar", "aside.sidebar"], "keep": [".sidebar-disclaimer"], "unwrap": [".layout", ".content-wrap"],
                 "css_drop": ["skip-link", "top-bar", "top-bar-inner", "top-bar-nav", "logo-link", "logo-text", "logo-dot", "nav-toggle",
                              "layout", "sidebar", "sidebar-logo", "site-label", "sidebar-nav", "nav-link", "on-this-page",
                              "on-this-page-label", "anchor-link", "sidebar-disclaimer", "content-wrap"]},
    "azqato.github.io": {"remove": ["body > nav"], "keep": [], "unwrap": [],
                         "css_drop": ["nav-inner", "nav-logo", "nav-toggle", "nav-links"]},
}
SCOPE = {"stocks": "src-stocks", "vix": "src-vix", "leverage": "src-leverage", "azqato.github.io": "src-invests"}

EM = "\u2014"
dash_log = []


# ---------- Em dashes (Question 14) ----------

DASH = re.compile(r"(\S?)(\s*)\u2014(\s*)(?=(\S?))")


def fix_dashes(text, where):
    """Replace em dashes used as punctuation between words: spaced ones with a
    single hyphen, unspaced ones with a comma (Writing Style). A lone dash that
    stands for a missing value, such as the screener's "(-)" written with an
    em dash or a quoted dash in a script, becomes an en dash (Question 19): the
    text needs a mark there, and the main repository's commit hook allows no em
    dash in any page."""
    if EM not in text:
        return text

    def rep(m):
        a, s1, s2, b = m.groups()
        if not (b and re.match(r"[\w($]", b)):
            return m.group(0)
        new = " - " if (s1 or s2) else ", "
        ctx = text[max(0, m.start() - 40): m.end() + 40].replace("\n", " ").strip()
        dash_log.append((where, ctx, new.strip()))
        return a + new
    text = DASH.sub(rep, text)
    for m in re.finditer(EM, text):
        ctx = text[max(0, m.start() - 40): m.end() + 40].replace("\n", " ").strip()
        dash_log.append((where, ctx, "– (placeholder)"))
    return text.replace(EM, "–")


# ---------- CSS scoping ----------

def blocks(css):
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out, i, n = [], 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            break
        semi = css.find(";", i)
        if 0 <= semi < j:
            i = semi + 1
            continue
        depth, k = 1, j + 1
        while k < n and depth:
            depth += {"{": 1, "}": -1}.get(css[k], 0)
            k += 1
        out.append((css[i:j].strip(), css[j + 1:k - 1]))
        i = k
    return out


KEEP_ROOT_PROPS = {"color", "font-family", "font-size", "line-height", "letter-spacing"}


def scope_css(css, scope, drop):
    out = []
    for pre, body in blocks(css):
        if pre.startswith("@media") or pre.startswith("@supports"):
            inner = scope_css(body, scope, drop)
            if inner.strip():
                out.append(f"{pre} {{\n{inner}}}\n")
            continue
        if pre.startswith("@"):
            out.append(f"{pre} {{{body}}}\n")
            continue
        sels = []
        root_rule = False
        for sel in (s.strip() for s in pre.split(",")):
            if not sel:
                continue
            classes = set(re.findall(r"\.([\w-]+)", sel))
            if classes & drop:
                continue
            m = re.match(r"^(:root|html|body)\b(.*)$", sel)
            if m:
                rest = re.sub(r"^\s*body\b", "", m.group(2))
                if not rest.strip():
                    root_rule = True
                    sels.append("." + scope)
                    continue
                sel = rest.strip() if rest.startswith(" ") else rest
                if not sel:
                    continue
                if not rest.startswith(" "):
                    sels.append("." + scope + sel)
                    continue
            bare = not re.search(r"[.#\[]", re.sub(r"::?[\w-]+(\([^)]*\))?", "", sel))
            if bare:
                continue
            sels.append(f".{scope} {sel}")
        if not sels:
            continue
        if root_rule:
            props = [p for p in body.split(";") if p.strip() and (p.strip().startswith("--") or p.split(":")[0].strip() in KEEP_ROOT_PROPS)]
            if not props:
                continue
            body = ";".join(props) + ";"
        out.append(",\n".join(sels) + " {" + body.rstrip() + "\n}\n")
    return "".join(out)


# ---------- Pages ----------

def rel(from_path, to_path):
    """Relative link from one page to another (or to the site root, "")."""
    if not to_path:
        return "../" * from_path.count("/")
    return posixpath.relpath(to_path, posixpath.dirname(from_path) or ".")


def map_href(href, repo, page):
    if not href or href.startswith(("#", "mailto:", "javascript:", "data:")):
        return href
    base, frag = (href.split("#", 1) + [""])[:2]
    frag = "#" + frag if "#" in href else ""
    m = COMPOSER_OLD.match(base)
    if m:
        return "https://composeratlas.com/" + m.group(1) + frag
    if base.startswith("http"):
        key = ("abs", base.rstrip("/") if base.rstrip("/") + "/" != base or ("abs", base) not in LINKS else base)
        for k in (("abs", base), ("abs", base.rstrip("/"))):
            if k in LINKS:
                return rel(page, LINKS[k]) + frag
        return href
    if repo == "azqato.github.io":
        name = base[:-5] if base.endswith(".html") else base
        if name == "index":
            return "https://azqato.com/" + frag
        if name == "invests":
            return rel(page, "index.html") + frag
        return f"https://azqato.com/{name}{frag}"
    if (repo, base) in LINKS:
        return rel(page, LINKS[(repo, base)]) + frag
    if base == "" and frag:
        return frag
    return href


def slug(text, used):
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:48] or "section"
    out, n = s, 2
    while out in used:
        out, n = f"{s}-{n}", n + 1
    used.add(out)
    return out


def read_source(src):
    return BeautifulSoup((SRC / src).read_text(encoding="utf-8"), "html.parser")


def extract(src, page):
    """The source page's body content, minus its site navigation, with links
    mapped. Returns (content soup fragment, scripts, head styles, description)."""
    repo = src.split("/")[0]
    soup = read_source(src)
    desc = soup.find("meta", attrs={"name": "description"})
    desc = desc["content"] if desc else ""
    styles = [s.string or "" for s in soup.head.find_all("style")] if soup.head else []
    body = soup.body
    for c in body.find_all(string=lambda t: isinstance(t, Comment)):
        c.extract()
    chrome = CHROME[repo]
    kept = []
    for sel in chrome["keep"]:
        for el in body.select(sel):
            kept.append(el.extract())
    for sel in chrome["remove"]:
        for el in body.select(sel):
            el.decompose()
    for sel in chrome["unwrap"]:
        for el in body.select(sel):
            el.unwrap()
    scripts = []
    for s in body.find_all("script"):
        scripts.append({"src": s.get("src"), "body": s.string or "", "attrs": {k: v for k, v in s.attrs.items() if k != "src"}})
        s.decompose()
    for m in body.find_all("main"):
        m.name = "div"
        m["class"] = ["src-main"] + m.get("class", [])
        if m.get("id") == "main-content":
            del m["id"]
    for f in body.find_all("footer"):
        f.name = "div"
        f["class"] = ["src-footer"] + f.get("class", [])
    if kept:
        box = soup.new_tag("div", attrs={"class": "src-footer src-footer--notes"})
        for el in kept:
            el.name = "p"
            box.append(el)
        body.append(box)
    for tag in body.find_all(["a", "area"]):
        if tag.get("href"):
            tag["href"] = map_href(tag["href"], repo, page)
    return soup, body, scripts, styles, desc


def dash_tree(node, where):
    for t in node.find_all(string=True):
        if isinstance(t, Comment):
            continue
        if EM in t:
            t.replace_with(NavigableString(fix_dashes(str(t), where)))
    for tag in node.find_all(True):
        for k, v in list(tag.attrs.items()):
            if isinstance(v, str) and EM in v:
                tag[k] = fix_dashes(v, where + f" ({k})")


def ensure_ids(article):
    used = {el["id"] for el in article.find_all(id=True)}
    for h in article.find_all(["h2", "h3"]):
        if not h.get("id"):
            h["id"] = slug(h.get_text(" ", strip=True), used)


def esc(s):
    return html.escape(s, quote=True)


# ---------- Page-specific moves ----------

def split_invests(body, part, soup, page):
    sections = body.find_all("section", recursive=False)
    hero, projects, resources = sections[0], sections[1], sections[2]
    footer = body.select_one(".src-footer")
    for a in hero.select("a.btn-discord"):
        a["href"] = "https://azqato.com/discord"
    if part == "home":
        cards = {"Stocks": "stocks/index.html", "Leveraged Strategies": "leveraged/index.html",
                 "VIX Strategy": "vix/index.html", "Stock Screener": "stocks/screener.html"}
        for a in projects.select("a.project-card"):
            name = a.h3.get_text(" ", strip=True).replace("→", "").strip()
            if name in cards:
                a["href"] = rel(page, cards[name])
                a.attrs.pop("target", None)
                a.attrs.pop("rel", None)
            elif name == "ComposerAtlas":
                a["href"] = "https://composeratlas.com/"
        # One grid (UI review, Home): this site's sections first, then the
        # outside projects. Every source card is kept; three are added for the
        # sections no source card covers.
        grid = projects.select_one(".project-grid")
        found = {a.h3.get_text(" ", strip=True).replace("\u2192", "").strip(): a for a in grid.select("a.project-card")}
        added = BeautifulSoup(home_cards(page), "html.parser")
        extra = {a.h3.get_text(" ", strip=True).replace("\u2192", "").strip(): a for a in added.select("a.project-card")}
        order = ["Stocks", "Stock Screener", "Market Overview & VIX tools", "VIX Strategy", "Leveraged Strategies",
                 "Curated Resources", "FAQ", "Automate Fundamentals", "ComposerAtlas", "Net Worth Tracker"]
        cards = [found.pop(n, None) or extra.pop(n) for n in order]
        cards += list(found.values())  # any card the source adds later
        for a in cards:
            grid.append(a.extract())
        return [hero, projects, footer]
    h2 = resources.find("h2")
    h2.name = "h1"
    return [resources, footer]


def home_cards(page):
    """Cards for the sections the source's project cards don't cover, in the
    source's own card markup."""
    cards = [
        ("\U0001F9F0", "Market Overview & VIX tools", "indices/market.html", "A same-day market snapshot, the live VIX Dashboard and the VIX Custom builder."),
        ("\U0001F4DA", "Curated Resources", "resources/index.html", "A hand-picked hub of platforms, screeners, education and data, in 15 categories."),
        ("\u2753", "FAQ", "resources/faq.html", "Answers to common questions about the methodology, the tools and the strategies."),
    ]
    used = set()
    return "".join(f'<a class="project-card" href="{rel(page, href)}"><span class="project-icon">{icon}</span>'
                   f'<h3 id="{slug(t, used)}">{esc(t)} <span class="arrow">\u2192</span></h3><p>{esc(d)}</p></a>'
                   for icon, t, href, d in cards)


ATLAS = {
    "leveraged/tqqq-ftlt.html": [
        ("TQQQ For The Long Term (original)", "https://composeratlas.com/strategies?slug=tqqq-long-term"),
        ("TQQQ For The Long Term, 2026 version", "https://composeratlas.com/strategies?slug=zoops-tqqq-long-term-2026"),
        ("UPRO FTLT, the S&P 500 counterpart", "https://composeratlas.com/strategies?slug=zoops-upro-ftlt-2026"),
    ],
    "leveraged/holy-grail.html": [
        ("Holy Grail (original)", "https://composeratlas.com/strategies?slug=holy-grail"),
        ("Holy Grail, 2026 version", "https://composeratlas.com/strategies?slug=zoops-holy-grail-2026"),
    ],
    "leveraged/hfea.html": [
        ("Composer Atlas database (search for symphony Cjb5ysKtJsPv6Tm3Fk0R)", "https://composeratlas.com/database.html"),
    ],
}


def atlas_box(page):
    items = "".join(f'<li><a href="{esc(u)}" target="_blank" rel="noopener">{esc(t)}</a></li>' for t, u in ATLAS[page])
    return (f'<aside class="pp-callout pp-callout--note site-atlas" aria-labelledby="atlas-h">'
            f'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 11v6M12 7.5v.5"/></svg>'
            f'<div><p id="atlas-h"><strong>On Composer Atlas</strong></p><ul>{items}</ul></div></aside>')


FAQ_FILTER = ('<div class="site-faq-filter"><label class="pp-label" for="faq-filter">Filter the questions</label>'
              '<input class="pp-input" id="faq-filter" type="search" autocomplete="off" placeholder="Type a word, like PEG or Palantir">'
              '<p class="pp-help" id="faq-filter-count" role="status"></p></div>')


# ---------- Shell ----------

def favicon():
    svg = "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>\U0001F4B0</text></svg>"
    return "data:image/svg+xml," + svg.replace("<", "%3C").replace(">", "%3E").replace("#", "%23")


def page_url(page):
    """The page's published address, as azqato.com serves it: index.html pages end
    at their folder, other pages drop .html (Cloudflare Pages' clean addresses)."""
    if page.endswith("index.html"):
        return SITE_URL + page[:-len("index.html")]
    return SITE_URL + page[:-len(".html")]


def head(page, title, desc, kind, scope, extra_css, inline_css):
    r = rel(page, "")
    css = ["theme.css", "base.css", "components.css", "docs.css", "site.css"] + extra_css
    links = "\n".join(f'<link rel="stylesheet" href="{r}assets/css/{c}">' for c in css)
    style = f"<style>\n{inline_css}</style>\n" if inline_css.strip() else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<meta name="description" content="{esc(desc)}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="{BRAND}">
<meta property="og:title" content="{esc(title)}">
<meta property="og:description" content="{esc(desc)}">
<meta property="og:url" content="{page_url(page)}">
<link rel="canonical" href="{page_url(page)}">
<meta name="twitter:card" content="summary">
<link rel="icon" href="{favicon()}">
<script src="{r}assets/js/theme.js"></script>
{links}
{style}</head>
"""


def topbar(page):
    r = rel(page, "")
    nav = "".join(
        f'<li><a href="{r}index.html" aria-current="true">{t}</a></li>' if u is None else f'<li><a href="{u}">{t}</a></li>'
        for t, u in AZQATO_NAV)
    return f"""<a class="site-skip" href="#pp-main">Skip to content</a>
<nav class="site-azqato" aria-label="Azqato.com">
  <a class="site-azqato-logo" href="https://azqato.com/">Azqato<span>.</span></a>
  <ul>{nav}</ul>
</nav>
<header class="pp-top">
  <button class="pp-menu-btn" id="pp-menu-btn" type="button" aria-expanded="false" aria-controls="pp-nav">
    <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"/></svg>
    <span class="pp-vh">Open navigation</span>
  </button>
  <a class="pp-logo site-logo" href="{r}index.html">
    <span class="site-logo-mark" aria-hidden="true">\U0001F4B0</span>
    <span class="pp-logo-name">{BRAND}</span>
  </a>
  <button class="pp-search-btn" id="pp-search-open" type="button" aria-haspopup="dialog" aria-keyshortcuts="/ Control+K">
    <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/></svg>
    <span class="pp-search-btn-text">Search the site</span>
    <kbd aria-hidden="true">/</kbd>
  </button>
  <div class="pp-top-end">
    <button class="pp-theme-btn theme-toggle" type="button" aria-label="Switch theme"><span class="theme-toggle-icon" aria-hidden="true"></span></button>
  </div>
</header>
"""


def sidebar(page):
    r = rel(page, "")

    def item(path, label, sub=False):
        cur = ' aria-current="page"' if path == page else ""
        cls = ' class="site-sub"' if sub else ""
        return f'<li{cls}><a href="{r}{path}"{cur}>{esc(label)}</a></li>'
    groups = [f'<div class="pp-group"><ul>{item("index.html", "Home")}</ul></div>']
    for g in GROUPS:
        gid = "pp-g-" + slug(g, set())
        members = [(p, label, parent) for p, _, label, grp, _, parent in PAGES if grp == g]
        lis = "".join(item(p, "Overview" if label == g else label) for p, label, parent in members)
        # Groups that don't hold this page start closed (UI review, Sidebar).
        opened = " open" if any(p == page for p, _, _ in members) else ""
        groups.append(f'<details class="pp-group site-group"{opened}><summary class="pp-group-label" id="{gid}">{g}</summary>'
                      f'<ul aria-labelledby="{gid}">{lis}</ul></details>')
    # azqato.com's links, shown here on phones, where its top bar is hidden (UI review).
    az = "".join(f'<li><a href="{u}">{t}</a></li>' for t, u in AZQATO_NAV if u)
    groups.append(f'<details class="pp-group site-group site-azqato-group"><summary class="pp-group-label" id="pp-g-azqato">Azqato.com</summary>'
                  f'<ul aria-labelledby="pp-g-azqato">{az}</ul></details>')
    return f"""<nav class="pp-sidebar" id="pp-nav" aria-label="Site sections">
  <div class="pp-sidebar-head">
    <p class="pp-sidebar-title">Contents</p>
    <button class="pp-nav-close" id="pp-nav-close" type="button">
      <svg viewBox="0 0 24 24" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg>
      <span class="pp-vh">Close navigation</span>
    </button>
  </div>
  {"".join(groups)}
  <div class="site-sidebar-foot"><div class="pp-sidebar-card"><p><strong>Educational use only.</strong><br>Not financial advice.</p></div></div>
</nav>
<div class="pp-scrim" id="pp-scrim" hidden></div>
"""


def crumbs(page, label, group, parent):
    if page == "index.html":
        return ""
    r = rel(page, "")
    parts = [f'<li><a href="{r}index.html">Home</a></li>']
    if group and label != group:
        landing = next(p for p, _, _, g, _, _ in PAGES if g == group)
        parts.append(f'<li><a href="{r}{landing}">{esc(group)}</a></li>')
    parts.append(f'<li><span aria-current="page">{esc(label)}</span></li>')
    return f'<nav class="pp-crumbs" aria-label="Breadcrumb"><ol>{"".join(parts)}</ol></nav>\n'


def pager(page):
    order = [p for p, *_ in PAGES]
    labels = {p: l for p, _, l, *_ in PAGES}
    i = order.index(page)
    r = rel(page, "")
    out = []
    if i > 0:
        p = order[i - 1]
        out.append(f'<a class="pp-pager-link pp-pager-link--prev" href="{r}{p}"><small>Previous</small><span>{esc(labels[p])}</span></a>')
    if i + 1 < len(order):
        p = order[i + 1]
        out.append(f'<a class="pp-pager-link pp-pager-link--next" href="{r}{p}"><small>Next</small><span>{esc(labels[p])}</span></a>')
    return f'<nav class="pp-pager" aria-label="Previous and next page">{"".join(out)}</nav>\n'


def footer(page, notes=""):
    r = rel(page, "")
    return f"""<footer class="pp-footer">
  <div class="pp-footer-in">
    <p class="pp-footer-brand">\U0001F4B0 {BRAND}</p>
    <p>Educational use only. Not financial advice. Some links are referral links.</p>{notes}
    <p><a href="{r}resources/index.html">Curated resources</a> · <a href="{r}resources/faq.html">FAQ</a> · Built by <a href="https://azqato.com/">Azqato</a></p>
  </div>
</footer>

<dialog class="pp-search" id="pp-search" aria-labelledby="pp-search-label">
  <div class="pp-search-box">
    <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.5 4.5"/></svg>
    <label class="pp-vh" id="pp-search-label" for="pp-search-input">Search the site</label>
    <input class="pp-search-input" id="pp-search-input" type="text" role="combobox" aria-expanded="true" aria-controls="pp-results" aria-autocomplete="list" autocomplete="off" spellcheck="false" placeholder="Search every page">
    <button class="pp-search-close" id="pp-search-close" type="button">Esc<span class="pp-vh"> Close search</span></button>
  </div>
  <p class="pp-results-head" id="pp-results-head">Popular</p>
  <ul class="pp-results" id="pp-results" role="listbox" aria-labelledby="pp-results-head"></ul>
  <p class="pp-vh" id="pp-search-count" role="status"></p>
  <p class="pp-search-foot"><kbd>Up</kbd> <kbd>Down</kbd> to move, <kbd>Enter</kbd> to open, <kbd>Esc</kbd> to close</p>
</dialog>
"""


# ---------- Scripts ----------

def page_scripts(page, repo, scripts):
    r = rel(page, "")
    out = []
    for s in scripts:
        src = s["src"]
        if src:
            if src.startswith("http"):
                if src == CHARTJS:
                    out.append(f'<script src="{CHARTJS}" integrity="{CHARTJS_SRI}" crossorigin="anonymous"></script>')
                else:
                    out.append(f'<script src="{esc(src)}"></script>')
                continue
            if repo == "vix" and src == "data/vix.js":
                out.append(f'<script src="{VIX_FEED}"></script>')
                continue
            if repo == "leverage" and src == "js/main.js":
                continue  # only drove the old sidebar; the shell does this now
            name = src.split("/")[-1]
            out.append(f'<script src="{r}assets/js/{repo}/{name}"></script>')
        else:
            js = s["body"]
            if repo == "azqato.github.io":
                continue  # only drove the old azqato.com nav toggle
            if s["attrs"].get("type") == "application/ld+json":
                continue
            js = repoint_js(js)
            if repo == "vix":
                js = vix_inline(js)
            js = fix_dashes(js, f"{page} (inline script)")
            out.append(f"<script>{js}</script>")
    return "\n".join(out)


def vix_inline(js):
    """UI review, VIX pages. A reading saved by another VIX page less than 30
    minutes ago (vix.js's REFRESH_TTL) is the same live reading, so it shows
    LIVE, not CACHED; STALE still marks an old one. The Custom builder words
    its tier line like the Dashboard."""
    js = js.replace("setStatus(data.stale ? 'stale' : data.fromCache ? 'cached' : 'live');",
                    "setStatus(data.stale ? 'stale' : 'live'); // Azqato Invests: a fresh saved reading is live")
    js = js.replace("const { getTier, getAllocation }     = window.VixStrategy;",
                    "const { getTier, getAllocation, getTierLabel } = window.VixStrategy;")
    js = js.replace("el.textContent = `VIX ${vixValue.toFixed(2)} \u2192 Tier: ${tier.replace('tier', '')}`;",
                    "el.textContent = `VIX ${vixValue.toFixed(2)} \u2192 ${getTierLabel(tier)}`; // Azqato Invests: as on the Dashboard")
    return js


FEED_CLEAN = ("/* Azqato Invests: feed text is shown as HTML, so angle brackets are dropped from it. */\n"
              "function azqClean(v) { if (typeof v === 'string') return v.replace(/[<>]/g, '');"
              " if (v && typeof v === 'object') { for (var k in v) v[k] = azqClean(v[k]); } return v; }\n")


def repoint_js(js):
    js = re.sub(r'(["\'])data/', lambda m: m.group(1) + STOCKS_DATA, js)
    if "await res.json()" in js and "fetch(" in js and "VixStrategy" not in js:
        js = FEED_CLEAN + js.replace("await res.json()", "azqClean(await res.json())")
    return js


def copy_scripts():
    pairs = [("stocks", SRC / "stocks/script.js"), ("stocks", SRC / "stocks/screener.js")]
    pairs += [("vix", p) for p in sorted((SRC / "vix/assets/js").glob("*.js"))]
    for repo, p in pairs:
        js = p.read_text(encoding="utf-8")
        if repo == "stocks":
            js = repoint_js(js)
        if p.name in ("strategy.js", "custom.js"):
            # Ticker colors as CSS variables (source hex as fallback) so they follow the theme.
            for name, hexv in (("bil", "#3b82f6"), ("spy", "#00ff88"), ("qqq", "#f59e0b"), ("tqqq", "#ef4444")):
                js = js.replace(f"color: '{hexv}',", f"color: 'var(--color-{name}, {hexv})', // Azqato Invests: follows the theme")
        if p.name == "chart.js":
            js = js.replace("""  const colors = [
    TICKERS.BIL.color,
    TICKERS.SPY.color,
    TICKERS.QQQ.color,
    TICKERS.TQQQ.color,
  ];""", r"""  // Ticker colors are var(--name, fallback) strings; the canvas needs the value.
  const colors = [TICKERS.BIL, TICKERS.SPY, TICKERS.QQQ, TICKERS.TQQQ].map((t) => {
    const m = /^var\((--[\w-]+),\s*([^)]+)\)$/.exec(t.color);
    return m ? cssVar(m[1], m[2]) : t.color;
  });""")
            js = js.replace("ctx.fillStyle = '#00ff88';", "ctx.fillStyle = cssVar('--accent-green', '#00ff88');")
            js = js.replace("ctx.shadowColor = 'rgba(0, 255, 136, 0.5)';", "ctx.shadowColor = cssVar('--accent-glow', 'rgba(0, 255, 136, 0.5)');")
            js = js.replace("ctx.fillStyle = '#6b7280';", "ctx.fillStyle = cssVar('--text-muted', '#6b7280');")
            js = js.replace("borderColor: '#0a0e1a',", "borderColor: cssVar('--bg-primary', '#0a0e1a'),")
            js = ("// Added by Azqato Invests: chart colors follow the page theme (read from the\n"
                  "// scoped vix tokens in assets/css/site.css), with the source colors as fallback.\n"
                  "function cssVar(name, fallback) {\n"
                  "  const el = document.querySelector('.src-vix') || document.documentElement;\n"
                  "  const v = getComputedStyle(el).getPropertyValue(name).trim();\n"
                  "  return v || fallback;\n}\n\n") + js
        js = fix_dashes(js, f"assets/js/{repo}/{p.name}")
        out = ROOT / "assets/js" / repo / p.name
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(js, encoding="utf-8", newline="\n")


def copy_template():
    css = ROOT / "assets/css"
    css.mkdir(parents=True, exist_ok=True)
    for name in ("theme.css", "base.css", "components.css"):
        shutil.copyfile(TPL / "assets/css" / name, css / name)
    docs = (TPL / "templates/documentation-site/styles.css").read_text(encoding="utf-8")
    docs = (f"/* Copied from Template Interface templates/documentation-site/styles.css at commit {TPL_COMMIT}.\n"
            "   Unchanged; this site's changes live in site.css. */\n") + docs
    (css / "docs.css").write_text(docs, encoding="utf-8", newline="\n")


FONT_SIZE = re.compile(r"font-size:\s*([\d.]+)(px|rem)")


def min_font(css):
    """No source text under 12px (UI review): px sizes below 12 and rem sizes
    below 0.75 are raised to that floor."""
    def fix(m):
        v, unit = float(m.group(1)), m.group(2)
        if unit == "px" and v < 12:
            return "font-size: 12px"
        if unit == "rem" and v < 0.75:
            return "font-size: 0.75rem"
        return m.group(0)
    return FONT_SIZE.sub(fix, css)


def source_css():
    out = ROOT / "assets/css"
    files = {"stocks": [SRC / "stocks/style.css"], "vix": [SRC / "vix/assets/css/styles.css"], "leverage": [SRC / "leverage/css/style.css"]}
    for repo, paths in files.items():
        css = "".join(p.read_text(encoding="utf-8") for p in paths)
        scoped = scope_css(css, SCOPE[repo], set(CHROME[repo]["css_drop"]))
        scoped = min_font(fix_dashes(scoped, f"assets/css/src-{repo}.css"))
        head = (f"/* Generated by scripts/site.py from {repo}'s stylesheet at the snapshot in _sources/COMMITS.txt.\n"
                f"   Every rule is scoped to .{SCOPE[repo]}; rules for the old site navigation and bare element\n"
                "   rules (the template styles plain text) are left out. Colors are mapped to the site's\n"
                "   themes in site.css. Don't edit; change scripts/site.py and run it again. */\n")
        (out / f"src-{repo}.css").write_text(head + scoped, encoding="utf-8", newline="\n")


# ---------- Build ----------

def build_page(entry, search):
    page, src, label, group, kind, parent = entry
    repo = src.split("/")[0]
    soup, body, scripts, styles, desc = extract(src, page)
    if repo == "azqato.github.io":
        part = "home" if page == "index.html" else "resources"
        nodes = split_invests(body, part, soup, page)
        if part == "resources":
            desc = "Curated investing resources from Azqato Invests: platforms, careers, screeners, education, data and news, in 15 categories. Some links are referral links."
    else:
        nodes = list(body.children)
    article = BeautifulSoup("", "html.parser")
    wrap = article.new_tag("div", attrs={"class": f"site-src {SCOPE[repo]}"})
    article.append(wrap)
    for n in nodes:
        wrap.append(n.extract() if hasattr(n, "extract") else n)
    if page in ATLAS:
        first = wrap.find("section")
        first.insert_before(BeautifulSoup(atlas_box(page), "html.parser"))
    if page == "resources/faq.html":
        h1 = wrap.find("h1")
        anchor = h1.find_parent("section") or h1
        anchor.insert_after(BeautifulSoup(FAQ_FILTER, "html.parser"))
    notes = merge_footers(wrap, repo)
    if page == "vix/custom.html":
        # The reading and tier first (UI review), then the ticker inputs, then the
        # chart and table they drive (author's request, 2026-10-02).
        wrap.find(id="chart-section").insert_before(wrap.find(id="customize").extract())
    dash_tree(wrap, page)
    ensure_ids(wrap)
    title = TITLES.get(page, f"{label} - {BRAND}")
    title = fix_dashes(title, page + " (title)")
    desc = fix_dashes(desc, page + " (description)")
    inline_css = "".join(scope_css(s, SCOPE[repo], set(CHROME[repo]["css_drop"])) for s in styles)
    inline_css = min_font(fix_dashes(inline_css, page + " (inline style)"))
    extra = [] if repo == "azqato.github.io" else [f"src-{repo}.css"]
    toc = "" if kind != "doc" else """<aside class="pp-toc" aria-labelledby="pp-toc-title">
  <p class="pp-toc-title" id="pp-toc-title">On this page</p>
  <ul class="pp-toc-list" id="pp-toc-list"></ul>
</aside>
"""
    content = str(article).replace(" viewbox=", " viewBox=")  # html.parser lowercases SVG attributes
    r = rel(page, "")
    doc = (head(page, title, desc, kind, SCOPE[repo], extra, inline_css)
           + f'<body class="pp-page site-page is-{kind}" data-root="{r}">\n'
           + topbar(page)
           + '<div class="pp-shell">\n' + sidebar(page)
           + '<main class="pp-main" id="pp-main" tabindex="-1">\n' + crumbs(page, label, group, parent)
           + f'<article class="pp-article" id="pp-article">\n{content}\n</article>\n'
           + pager(page) + "</main>\n" + toc + "</div>\n"
           + footer(page, fix_dashes(notes, page + " (footer)"))
           + f'<script src="{r}assets/js/site.js"></script>\n'
           + page_scripts(page, repo, scripts) + "\n</body>\n</html>\n")
    out = ROOT / page
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(doc, encoding="utf-8", newline="\n")
    index_page(page, label, group, wrap, search)


def merge_footers(wrap, repo):
    """One footer per page (UI review). The source footers that only repeat the
    site footer ("Built by Azqato", "Educational use only. Not financial advice.")
    stay in the page, hidden (class site-dup). The VIX pages' disclaimer and
    copyright lines move into the site footer; their call-to-action stays."""
    notes = []
    for f in wrap.select(".src-footer"):
        disc = f.select_one(".footer-disclaimer")
        if repo == "vix" and disc:
            for p in disc.find_all("p"):
                p["class"] = p.get("class", []) + ["site-footer-note"]
                if p.get_text(" ", strip=True).startswith("Built by"):
                    p["class"] = p["class"] + ["site-dup"]
                notes.append(str(p))
            disc.decompose()
        elif not f.select_one(".footer-cta"):
            f["class"] = f.get("class", []) + ["site-dup"]
    return "".join("\n    " + n for n in notes)


def index_page(page, label, group, wrap, search):
    pi = len(search["pages"])
    search["pages"].append({"u": page, "t": label if page != "index.html" else "Home", "g": group or "Home"})
    entry = {"p": pi, "h": label, "a": "", "x": ""}
    for el in wrap.find_all(["h1", "h2", "h3", "p", "li", "td", "th", "dt", "dd", "button", "figcaption", "summary"]):
        if el.name in ("h2", "h3") and el.get("id"):
            search["entries"].append(entry)
            entry = {"p": pi, "h": el.get_text(" ", strip=True), "a": el["id"], "x": ""}
        elif el.name != "h1" and not el.find(["p", "li", "td", "dt", "dd"]):
            entry["x"] += " " + el.get_text(" ", strip=True)
    search["entries"].append(entry)


def main():
    copy_template()
    source_css()
    copy_scripts()
    search = {"pages": [], "entries": []}
    for entry in PAGES:
        build_page(entry, search)
    for e in search["entries"]:
        e["x"] = re.sub(r"\s+", " ", e["x"]).strip()
    (ROOT / "assets/js/search-index.js").write_text(
        "// Generated by scripts/site.py: every page's sections, for the site search.\n"
        "window.SITE_INDEX = " + json.dumps(search, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8", newline="\n")
    # sitemap.xml for the published address. robots.txt belongs at the origin
    # (azqato.github.io), which this site doesn't own; see the PRD Runbook.
    urls = "".join(f"  <url><loc>{page_url(path)}</loc></url>\n" for path, *_ in PAGES)
    (ROOT / "sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n'
                                      '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
                                      + urls + "</urlset>\n", encoding="utf-8", newline="\n")
    mp = {}
    for path, src, *_ in PAGES:
        repo, name = src.split("/")
        mp.setdefault(f"{repo}-{name[:-5]}.json", []).append(path)
    (ROOT / "inventory/map.json").write_text(json.dumps(mp, indent=1) + "\n", encoding="utf-8", newline="\n")
    lines = ["# Em dashes replaced", "", "Generated by scripts/site.py (Question 14). Each em dash used as punctuation in moved text,",
             "with its place, the text around it and what replaced it. Lone dashes that stand for a missing value are kept.", "",
             "| Where | Text around it | Replaced with |", "|---|---|---|"]
    for where, ctx, new in dash_log:
        lines.append(f"| {where} | {ctx.replace('|', '/').replace(EM, '(em dash)')} | `{new}` |")
    (ROOT / "inventory/em-dashes.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{len(PAGES)} pages, {len(search['entries'])} search entries, {len(dash_log)} em dashes replaced")


if __name__ == "__main__":
    main()
