/*
 * The site search in the second bar on azqato.com's pages (owner's request,
 * 2026-10-03: the bar matches Azqato Invests'). Adapted from Invests' search
 * (invests/assets/js/site.js): the same scoring, keyboard use and look. It
 * searches every root page and every Invests section.
 *
 * The index (search-index.js, generated by scripts/build-nav.py) loads on first
 * use, so pages don't download every page's text up front. Opens with the
 * button, "/" or Ctrl+K.
 */
(function () {
  "use strict";

  var me = document.currentScript;
  var ROOT = me ? me.getAttribute("src").replace(/search\.js$/, "") : "";
  var POPULAR = ["invests/stocks/screener.html", "invests/indices/vix/index.html", "projects/index.html", "discord/index.html"];

  var openBtn = document.querySelector(".site-search-btn");
  if (!openBtn) return;

  function esc(s) {
    return String(s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c];
    });
  }

  var dialog = document.createElement("dialog");
  dialog.className = "site-search";
  dialog.setAttribute("aria-labelledby", "site-search-label");
  dialog.innerHTML =
    "<div class=\"site-search-box\">" +
    "<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><circle cx=\"11\" cy=\"11\" r=\"6.5\"/><path d=\"m16 16 4.5 4.5\"/></svg>" +
    "<label class=\"site-vh\" id=\"site-search-label\" for=\"site-search-input\">Search the site</label>" +
    "<input class=\"site-search-input\" id=\"site-search-input\" type=\"text\" role=\"combobox\" aria-expanded=\"true\" aria-controls=\"site-results\" aria-autocomplete=\"list\" autocomplete=\"off\" spellcheck=\"false\" placeholder=\"Search every page\">" +
    "<button class=\"site-search-close\" type=\"button\">Esc<span class=\"site-vh\"> Close search</span></button>" +
    "</div>" +
    "<p class=\"site-results-head\" id=\"site-results-head\">Popular</p>" +
    "<ul class=\"site-results\" id=\"site-results\" role=\"listbox\" aria-labelledby=\"site-results-head\"></ul>" +
    "<p class=\"site-search-empty\" hidden></p>" +
    "<p class=\"site-vh\" role=\"status\"></p>" +
    "<p class=\"site-search-foot\"><kbd>Up</kbd> <kbd>Down</kbd> to move, <kbd>Enter</kbd> to open, <kbd>Esc</kbd> to close</p>";
  document.body.appendChild(dialog);

  var input = dialog.querySelector(".site-search-input");
  var closeBtn = dialog.querySelector(".site-search-close");
  var results = dialog.querySelector(".site-results");
  var resultsHead = dialog.querySelector(".site-results-head");
  var empty = dialog.querySelector(".site-search-empty");
  var count = dialog.querySelector("[role=status]");

  var index = null;
  var loading = false;

  function loadIndex(done) {
    if (index) return done();
    if (window.SITE_INDEX) {
      index = window.SITE_INDEX;
      return done();
    }
    if (loading) return;
    loading = true;
    var s = document.createElement("script");
    s.src = ROOT + "search-index.js";
    s.onload = function () { index = window.SITE_INDEX; loading = false; done(); };
    s.onerror = function () { loading = false; resultsHead.textContent = "Search couldn't load. Try again."; };
    document.head.appendChild(s);
  }

  var shown = [];
  var active = -1;
  var countTimer;

  function mark(text, terms) {
    var out = esc(text);
    terms.forEach(function (t) {
      var re = new RegExp("(" + esc(t).replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")", "ig");
      out = out.replace(re, "<mark>$1</mark>");
    });
    return out;
  }

  function snippet(text, terms) {
    var low = text.toLowerCase();
    var at = -1;
    terms.forEach(function (t) {
      var i = low.indexOf(t);
      if (i !== -1 && (at === -1 || i < at)) at = i;
    });
    if (at === -1) return text.length > 110 ? text.slice(0, 110).replace(/\s\S*$/, "") + "..." : text;
    var start = Math.max(0, at - 40);
    var end = Math.min(text.length, at + 90);
    var s = text.slice(start, end);
    if (start > 0) s = "..." + s.replace(/^\S*\s/, "");
    if (end < text.length) s = s.replace(/\s\S*$/, "") + "...";
    return s;
  }

  function search(q) {
    var terms = q.toLowerCase().split(/\s+/).filter(Boolean);
    var found = [];
    index.entries.forEach(function (e) {
      var page = index.pages[e.p];
      var head = e.h.toLowerCase();
      var title = page.t.toLowerCase();
      var text = e.x.toLowerCase();
      var score = 0;
      for (var i = 0; i < terms.length; i++) {
        var t = terms[i];
        var inHead = head.indexOf(t) !== -1;
        var inTitle = title.indexOf(t) !== -1;
        var hits = text.split(t).length - 1;
        if (!inHead && !inTitle && !hits) return;
        score += (inHead ? 10 : 0) + (inTitle ? 4 : 0) + Math.min(hits, 5);
      }
      if (!e.a) score += 2;
      found.push({ e: e, score: score });
    });
    found.sort(function (a, b) { return b.score - a.score; });
    return { terms: terms, list: found.slice(0, 8).map(function (f) { return f.e; }) };
  }

  function setActive(i) {
    var items = results.children;
    if (active > -1 && items[active]) items[active].setAttribute("aria-selected", "false");
    active = i;
    if (i > -1 && items[i]) {
      items[i].setAttribute("aria-selected", "true");
      input.setAttribute("aria-activedescendant", items[i].id);
      items[i].scrollIntoView({ block: "nearest" });
    } else {
      input.removeAttribute("aria-activedescendant");
    }
  }

  function paintResults() {
    if (!index) return;
    var q = input.value.trim();
    var terms = [];
    if (q) {
      var r = search(q);
      shown = r.list;
      terms = r.terms;
      resultsHead.textContent = shown.length ? "Results" : "No results";
    } else {
      var urls = index.pages.map(function (p) { return p.u; });
      shown = POPULAR.map(function (u) {
        var pi = urls.indexOf(u);
        return index.entries.filter(function (e) { return e.p === pi && !e.a; })[0];
      }).filter(Boolean);
      resultsHead.textContent = "Popular";
    }

    results.textContent = "";
    shown.forEach(function (e, i) {
      var p = index.pages[e.p];
      var li = document.createElement("li");
      li.id = "site-opt-" + i;
      li.className = "site-result";
      li.setAttribute("role", "option");
      li.setAttribute("aria-selected", "false");
      li.setAttribute("data-href", ROOT + p.u + (e.a ? "#" + e.a : ""));
      li.innerHTML =
        "<span class=\"site-r-crumb\">" + esc(p.g) + " / " + esc(p.t) + "</span>" +
        "<span class=\"site-r-title\">" + mark(e.h, terms) + "</span>" +
        "<span class=\"site-r-snip\">" + mark(snippet(e.x, terms), terms) + "</span>";
      results.appendChild(li);
    });

    empty.hidden = !(q && !shown.length);
    if (!empty.hidden) {
      empty.textContent = "Nothing matches “" + q + "”. Try one word, like “Discord” or “VIX”.";
    }
    results.hidden = !shown.length;
    active = -1;
    setActive(shown.length ? 0 : -1);

    clearTimeout(countTimer);
    countTimer = setTimeout(function () {
      count.textContent = q ? (shown.length ? shown.length + (shown.length === 1 ? " result" : " results") : "No results") : "";
    }, 400);
  }

  function openSearch() {
    if (dialog.open) return;
    dialog.showModal();
    if (!index) resultsHead.textContent = "Loading";
    loadIndex(paintResults);
    input.select();
  }

  function choose(i) {
    var li = results.children[i];
    if (!li) return;
    dialog.close();
    window.location.href = li.getAttribute("data-href");
  }

  openBtn.addEventListener("click", openSearch);
  closeBtn.addEventListener("click", function () { dialog.close(); });
  dialog.addEventListener("click", function (event) {
    if (event.target === dialog) dialog.close();
  });
  input.addEventListener("input", paintResults);
  input.addEventListener("keydown", function (event) {
    var n = results.children.length;
    if (event.key === "ArrowDown" && n) {
      event.preventDefault();
      setActive((active + 1) % n);
    } else if (event.key === "ArrowUp" && n) {
      event.preventDefault();
      setActive((active - 1 + n) % n);
    } else if (event.key === "Enter") {
      event.preventDefault();
      if (active > -1) choose(active);
    }
  });
  results.addEventListener("mousemove", function (event) {
    var li = event.target.closest(".site-result");
    if (li) {
      var i = [].indexOf.call(results.children, li);
      if (i !== active) setActive(i);
    }
  });
  results.addEventListener("click", function (event) {
    var li = event.target.closest(".site-result");
    if (li) choose([].indexOf.call(results.children, li));
  });

  document.addEventListener("keydown", function (event) {
    var el = document.activeElement;
    var typing = el && (/^(INPUT|TEXTAREA|SELECT)$/.test(el.tagName) || el.isContentEditable);
    if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {
      event.preventDefault();
      openSearch();
    } else if (event.key === "/" && !typing && !dialog.open) {
      event.preventDefault();
      openSearch();
    }
  });
})();
